#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="examples/BasicBleKissTnc"
OUT_FILE="${1:-$PROJECT_DIR/resource-baseline.env}"

TMP_LOG="$(mktemp)"
trap 'rm -f "$TMP_LOG"' EXIT

pio run -d "$PROJECT_DIR" >"$TMP_LOG" 2>&1

RAM_USED="$(grep -E 'RAM:.*\(used [0-9]+ bytes from [0-9]+ bytes\)' "$TMP_LOG" | sed -E 's/.*\(used ([0-9]+) bytes from ([0-9]+) bytes\).*/\1/' | tail -n1)"
RAM_TOTAL="$(grep -E 'RAM:.*\(used [0-9]+ bytes from [0-9]+ bytes\)' "$TMP_LOG" | sed -E 's/.*\(used ([0-9]+) bytes from ([0-9]+) bytes\).*/\2/' | tail -n1)"
FLASH_USED="$(grep -E 'Flash:.*\(used [0-9]+ bytes from [0-9]+ bytes\)' "$TMP_LOG" | sed -E 's/.*\(used ([0-9]+) bytes from ([0-9]+) bytes\).*/\1/' | tail -n1)"
FLASH_TOTAL="$(grep -E 'Flash:.*\(used [0-9]+ bytes from [0-9]+ bytes\)' "$TMP_LOG" | sed -E 's/.*\(used ([0-9]+) bytes from ([0-9]+) bytes\).*/\2/' | tail -n1)"

if [[ -z "$RAM_USED" || -z "$FLASH_USED" ]]; then
  echo "Failed to parse RAM/Flash usage from build output" >&2
  cat "$TMP_LOG" >&2
  exit 1
fi

cat > "$OUT_FILE" <<BASE
# Generated by scripts/resource_snapshot.sh
RAM_USED=$RAM_USED
RAM_TOTAL=$RAM_TOTAL
FLASH_USED=$FLASH_USED
FLASH_TOTAL=$FLASH_TOTAL
BASE

echo "Wrote baseline: $OUT_FILE"
cat "$OUT_FILE"
